--S-2 Emil
insert into teacher_discipline values (1, 1)
insert into teacher_discipline values (2, 1)
insert into teacher_discipline values (3, 1)
insert into teacher_discipline values (4, 1)
insert into teacher_discipline values (2, 2)
insert into teacher_discipline values (4, 2)
insert into teacher_discipline values (3, 3)
insert into teacher_discipline values (4, 3)
insert into teacher_discipline values (5, 3)
insert into teacher_discipline values (6, 3)
insert into teacher_discipline values (7, 4)
insert into teacher_discipline values (8, 4)
insert into teacher_discipline values (9, 4)