--S-2 Emil
insert into teacher_discipline values (1, 1)
insert into teacher_discipline values (1, 2)
insert into teacher_discipline values (1, 3)
insert into teacher_discipline values (1, 4)
insert into teacher_discipline values (2, 2)
insert into teacher_discipline values (2, 4)
insert into teacher_discipline values (3, 3)
insert into teacher_discipline values (3, 4)
insert into teacher_discipline values (3, 5)
insert into teacher_discipline values (3, 6)
insert into teacher_discipline values (4, 7)
insert into teacher_discipline values (4, 8)
insert into teacher_discipline values (4, 9)